apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  app-graphql
  labels:
    name: app-graphql-deployment
    app: app-graphql
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  my-name
        app: app-graphql
    spec:
      restartPolicy: Always
      containers:
      - image: gcr.io/green-buttress-260810/gcloud.graphql:alpha  
        imagePullPolicy: Always
        name: api-app
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
          limits:
            cpu: "20m"
            memory : "55M"
        livenessProbe:
          httpGet:
            path: /status/healthz
            port: 3000
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /status/healthz
            port: 3000
          initialDelaySeconds: 30
          timeoutSeconds: 10
        # env:
        # - name:  ENVVARNAME
        #   value:  ENVVARVALUE       
        ports:
        - containerPort:  3000
          name:  my-name
        # volumeMounts:
        # - mountPath: /data
        #   name: data
      # volumes:
      #   - name: data
      #     emptyDir: {}
---
kind: Service
apiVersion: v1
metadata:
  name:  app-graphql-service
spec:
  type: NodePort
  selector:
    app:  app-graphql
  # type:  LoadBalancer
  ports:
  - name:  http
    port:  2000
    targetPort:  2000
