apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  expo-api  
  labels:
    name: expo-api-deployment
    app: expo-api
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  my-name
        app: expo-api
    spec:
      restartPolicy: Always
      containers:
      - image: gcr.io/green-buttress-260810/gcloud.graphql:alpha-v0.2
        imagePullPolicy: Always
        name: api-app
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
          limits:
            cpu: "20m"
            memory : "55M"
        livenessProbe:
          httpGet:
            path: /status/healthz
            port: 80
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /status/healthz
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 10
        # env:
        # - name:  ENVVARNAME
        #   value:  ENVVARVALUE       
        ports:
        - containerPort:  80
          name:  expo-api
        # volumeMounts:
        # - mountPath: /data
        #   name: data
      # volumes:
      #   - name: data
      #     emptyDir: {}
---
kind: Service
apiVersion: v1
metadata:
  name:  expo-api-service
spec:
  type: NodePort
  selector:
    app:  expo-api
  # type:  LoadBalancer
  ports:
  - name:  http
    port:  80
    targetPort:  80
